"""baseline from sqlmodel state

Revision ID: cf842bbfaeb5
Revises: 
Create Date: 2026-05-01 11:13:18.689645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf842bbfaeb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market', sa.Enum('DE', 'US', 'INT', 'MIXED', 'UNKNOWN', name='market'), nullable=False),
    sa.Column('channel_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Enum('A', 'B', 'C', name='priority'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('mvp', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title_original', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_local', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('franchise', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_relevance', sa.Enum('DE', 'US', 'INT', 'MIXED', 'UNKNOWN', name='market'), nullable=False),
    sa.Column('release_date_de', sa.Date(), nullable=True),
    sa.Column('release_date_us', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('A', 'B', 'C', name='priority'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_tmdb_id'), 'title', ['tmdb_id'], unique=False)
    op.create_table('titlesyncrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('markets', sa.JSON(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('upserted_count', sa.Integer(), nullable=False),
    sa.Column('deduped_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeklyreport',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'FINAL', name='reportstatus'), nullable=False),
    sa.Column('executive_summary_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executive_summary_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trend_summary_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('visible_likes', sa.Integer(), nullable=True),
    sa.Column('visible_comments', sa.Integer(), nullable=True),
    sa.Column('visible_views', sa.Integer(), nullable=True),
    sa.Column('visible_shares', sa.Integer(), nullable=True),
    sa.Column('visible_bookmarks', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_post_url'), 'post', ['post_url'], unique=True)
    op.create_table('titlekeyword',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keyword_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('title_id', sa.Uuid(), nullable=True),
    sa.Column('asset_type', sa.Enum('TRAILER', 'TRAILER_DROP', 'TEASER', 'POSTER', 'KEY_ART', 'STORY', 'KINETIC', 'CHARACTER_CARD', 'CAST_POST', 'REVIEW_QUOTE', 'CTA_POST', 'TICKET_CTA', 'RELEASE_REMINDER', 'BEHIND_THE_SCENES', 'EVENT_FESTIVAL', 'SERIES_EPISODE_PUSH', 'FRANCHISE_BRAND_POST', 'DISCOVERY', 'UNKNOWN', name='assettype'), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('screenshot_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_keywords', sa.JSON(), nullable=True),
    sa.Column('ai_summary_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_summary_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_trend_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('NEW', 'APPROVED', 'HIGHLIGHT', 'REJECTED', 'NEEDS_REVIEW', name='reviewstatus'), nullable=False),
    sa.Column('curator_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('is_highlight', sa.Boolean(), nullable=False),
    sa.Column('visual_analysis_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('placement_title_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('placement_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('placement_strength', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_title_placement', sa.Boolean(), nullable=False),
    sa.Column('has_kinetic', sa.Boolean(), nullable=False),
    sa.Column('kinetic_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kinetic_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('de_us_match_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_confidence_score', sa.Float(), nullable=True),
    sa.Column('visual_evidence_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_crop_title_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_crop_cta_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_crop_kinetic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_evidence_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_evidence_pack', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titlecandidate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggested_franchise', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('HASHTAG', 'TEXT', 'OCR', 'OPENAI', 'PERPLEXITY', 'MATCHER', name='candidatesource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'IGNORED', name='candidatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titlecandidate_asset_id'), 'titlecandidate', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titlecandidate_asset_id'), table_name='titlecandidate')
    op.drop_table('titlecandidate')
    op.drop_table('asset')
    op.drop_table('titlekeyword')
    op.drop_index(op.f('ix_post_post_url'), table_name='post')
    op.drop_table('post')
    op.drop_table('weeklyreport')
    op.drop_table('titlesyncrun')
    op.drop_index(op.f('ix_title_tmdb_id'), table_name='title')
    op.drop_table('title')
    op.drop_table('channel')
    # ### end Alembic commands ###
